Refactor xenserver driver
Autodetect vbd-create instead of trying to figure it out.

diff --git a/driver/xenserver b/driver/xenserver
--- a/driver/xenserver
+++ b/driver/xenserver
@@ -4,248 +4,215 @@ JQ="/usr/libexec/kubernetes/kubelet-plugins/volume/exec/spangenberg.io~xenserver
 LOG_FILE="/tmp/xenserver-driver.log"
 
 debug() {
-	echo -e $* >> $LOG_FILE 2>&1
+	echo "$*" >> ${LOG_FILE} 2>&1
 }
 
 err() {
-	echo -ne $* 1>&2
+	echo "$*" 1>&2
 }
 
 log() {
-	echo -ne $* >&1
+	echo "$*" >&1
 }
 
-in_array() {
-	local elements element=$1
-	shift
-	for elements; do
-		[[ $elements == $element ]] && return 0
-	done
-	return 1
+failure() {
+	err "{\"status\": \"Failure\", \"message\": \"$*\"}"
+	exit 1
 }
 
-not_in_array() {
-	if in_array $@; then
-		return 1
-	else
-		return 0
-	fi
+success() {
+	debug "success"
+	log '{"status": "Success"}'
+	exit 0
 }
 
 init() {
-	log "{\"status\": \"Success\", \"capabilities\": {\"attach\": false}}"
+	log '{"status": "Success", "capabilities": {"attach": false}}'
 	exit 0
 }
 
 domount() {
-	MOUNT_DIR="$1"
-	debug "MOUNT_DIR=$MOUNT_DIR"
-	JSON_OPTIONS="$2"
-	debug "JSON_OPTIONS=$JSON_OPTIONS"
+	mount_dir=${1}
+	debug "mount_dir=${mount_dir}"
+	json_options=${2}
+	debug "json_options=${json_options}"
 
-	FS_TYPE=$(echo "$JSON_OPTIONS" | $JQ -r '.["kubernetes.io/fsType"]')
-	if [[ -z "$FS_TYPE" ]]; then
-		FS_TYPE="ext4"
+	fs_type=$(echo "${json_options}" | ${JQ} -r '.["kubernetes.io/fsType"]')
+	if [[ -z "${fs_type}" ]]; then
+		fs_type="ext4"
 	fi
 
-	VDI_NAME_LABEL=$(echo $JSON_OPTIONS | $JQ -r '.["kubernetes.io/pvOrVolumeName"]')
-	XENSERVER_PASSWORD=$(echo $JSON_OPTIONS | $JQ -r '.["spangenberg.io/xenserver/password"]')
-	XENSERVER_USERNAME=$(echo $JSON_OPTIONS | $JQ -r '.["spangenberg.io/xenserver/username"]')
-	XENSERVER_HOST=$(echo $JSON_OPTIONS | $JQ -r '.["spangenberg.io/xenserver/host"]')
+	vdi_name_label=$(echo "${json_options}" | ${JQ} -r '.["kubernetes.io/pvOrVolumeName"]')
+	xenserver_password=$(echo "${json_options}" | ${JQ} -r '.["spangenberg.io/xenserver/password"]')
+	xenserver_username=$(echo "${json_options}" | ${JQ} -r '.["spangenberg.io/xenserver/username"]')
+	xenserver_host=$(echo "${json_options}" | ${JQ} -r '.["spangenberg.io/xenserver/host"]')
 
-	MAC=$(cat /sys/class/net/eth0/address 2>>$LOG_FILE)
+	mac=$(cat /sys/class/net/eth0/address 2>>${LOG_FILE})
 	if [ $? -ne 0 ]; then
-		err "{\"status\": \"Failure\", \"message\": \"Could not get mac address\"}"
-		exit 1
+		failure "Could not get mac address"
 	fi
 
-	VM_ID=$(xapi "$XENSERVER_HOST" "$XENSERVER_USERNAME" "$XENSERVER_PASSWORD" vif-list currently-attached="true" MAC="$MAC" params="vm-uuid" --minimal)
+	vm_uuid=$(xapi "${xenserver_host}" "${xenserver_username}" "${xenserver_password}" vif-list currently-attached=true MAC=${mac} params=vm-uuid --minimal)
 	if [ $? -ne 0 ]; then
-		err "{\"status\": \"Failure\", \"message\": \"Could not list vif\"}"
-		exit 1
+		failure "Could not list vif"
 	fi
-	if [[ -z "$VM_ID" ]]; then
-		err "{\"status\": \"Success\", \"message\": \"Could not find VM with MAC $MAC\"}"
-		exit 1
+	if [[ -z "${vm_uuid}" ]]; then
+		failure "Could not find VM with MAC ${mac}"
 	fi
 
-	VDI_ID=$(xapi "$XENSERVER_HOST" "$XENSERVER_USERNAME" "$XENSERVER_PASSWORD" vdi-list is-a-snapshot="false" name-label="$VDI_NAME_LABEL" --minimal)
+	vdi_uuid=$(xapi "${xenserver_host}" "${xenserver_username}" "${xenserver_password}" vdi-list is-a-snapshot=false name-label=${vdi_name_label} --minimal)
 	if [ $? -ne 0 ]; then
-		err "{\"status\": \"Failure\", \"message\": \"Could not list vdi\"}"
-		exit 1
+		failure "Could not list vdi"
 	fi
-	if [[ -z "$VDI_ID" ]]; then
-		err "{\"status\": \"Success\", \"message\": \"Could not find VDI\"}"
-		exit 1
+	if [[ -z "${vdi_uuid}" ]]; then
+		failure "Could not find VDI"
 	fi
 
-	DEVICES=$(xapi "$XENSERVER_HOST" "$XENSERVER_USERNAME" "$XENSERVER_PASSWORD" vbd-list currently-attached="true" params="device" vm-uuid="$VM_ID" --minimal)
+	vbd_uuids=$(xapi "${xenserver_host}" "${xenserver_username}" "${xenserver_password}" vbd-list vdi-uuid=${vdi_uuid} --minimal)
 	if [ $? -ne 0 ]; then
-		err "{\"status\": \"Failure\", \"message\": \"Could not list vbd\"}"
-		exit 1
+		failure "Could not list vbds"
 	fi
-	if [[ -z "$DEVICES" ]]; then
-		err "{\"status\": \"Success\", \"message\": \"Could not find devices\"}"
-		exit 1
-	fi
-
-	OIFS="$IFS"; IFS=","; DEVS=($DEVICES); IFS="$OIFS"
-	for a in {b..z}; do
-		device="xvd$a"
-		if not_in_array	$device ${DEVS[@]}; then
-			DEVICE=$device
-			break
-		fi
-	done
-	if [ -z $DEVICE ]; then
-		for a in {a..z}; do
-			for b in {a..z}; do
-				device="xvd$a$b"
-				if not_in_array	$device ${DEVS[@]}; then
-					DEVICE=$device
-					break
+	if [[ -n "${vbd_uuids}" ]]; then
+		OIFS=${IFS}; IFS=","; vbd_uuids=("${vbd_uuids}"); IFS=${OIFS}
+		for vbd_uuid in "${vbd_uuids[@]}"; do
+			currently_attached=$(xapi "${xenserver_host}" "${xenserver_username}" "${xenserver_password}" vbd-list uuid=${vbd_uuid} params=currently-attached --minimal)
+			if [ $? -ne 0 ]; then
+				failure "Could not list vbd"
+			fi
+			if [ "${currently_attached}" = "true" ]; then
+				xapi "${xenserver_host}" "${xenserver_username}" "${xenserver_password}" vbd-unplug uuid=${vbd_uuid} force=true
+				if [ $? -ne 0 ]; then
+					failure "Could not unplug vbd"
 				fi
-			done
-			if [ -n $DEVICE ]; then
-				break
+			fi
+
+			xapi "${xenserver_host}" "${xenserver_username}" "${xenserver_password}" vbd-destroy uuid=${vbd_uuid}
+			if [ $? -ne 0 ]; then
+				failure "Could not destroy vbd"
 			fi
 		done
 	fi
-	if [[ -z "$DEVICE" ]]; then
-		err "{\"status\": \"Success\", \"message\": \"Could not find device\"}"
-		exit 1
+
+	vbd_uuid=$(xapi "${xenserver_host}" "${xenserver_username}" "${xenserver_password}" vbd-create vm-uuid=${vm_uuid} vdi-uuid=${vdi_uuid} device=autodetect)
+	if [ $? -ne 0 -o -z "${vbd_uuid}" ]; then
+		failure "Could not create vbd"
 	fi
 
-	VBD_ID=$(xapi "$XENSERVER_HOST" "$XENSERVER_USERNAME" "$XENSERVER_PASSWORD" vbd-create vm-uuid="$VM_ID" vdi-uuid="$VDI_ID" device="$DEVICE" type="Disk" mode="RW")
+	xapi "${xenserver_host}" "${xenserver_username}" "${xenserver_password}" vbd-plug uuid=${vbd_uuid}
 	if [ $? -ne 0 ]; then
-		err "{\"status\": \"Failure\", \"message\": \"Could not create vbd\"}"
-		exit 1
+		failure "Could not plug vbd"
 	fi
 
-	xapi "$XENSERVER_HOST" "$XENSERVER_USERNAME" "$XENSERVER_PASSWORD" vbd-plug uuid="$VBD_ID"
-	if [ $? -ne 0 ]; then
-		err "{\"status\": \"Failure\", \"message\": \"Could not plug vbd\"}"
-		exit 1
+	device=$(xapi "${xenserver_host}" "${xenserver_username}" "${xenserver_password}" vbd-param-get uuid=${vbd_uuid} param-name=device)
+	if [ $? -ne 0 -o -z "${device}" ]; then
+		failure "Could get vbd param"
 	fi
 
-	BLK_ID=$(blkid /dev/"$DEVICE" 2>>$LOG_FILE)
-	if [ -z "$BLK_ID" ]; then
-		debug "sh -c 'mkfs -t $FS_TYPE /dev/$DEVICE'"
-		mkfs -t "$FS_TYPE" /dev/"$DEVICE" >> $LOG_FILE 2>&1
+	debug "blkid /dev/${device}"
+	if [ -z "$(blkid "/dev/${device}" 2>>${LOG_FILE})" ]; then
+		debug "mkfs -t ${fs_type} /dev/${device}"
+		mkfs -t "${fs_type}" "/dev/${device}" >> ${LOG_FILE} 2>&1
 		if [ $? -ne 0 ]; then
-			err "{\"status\": \"Failure\", \"message\": \"Failed to create fs $FS_TYPE on device $DEVICE\"}"
-			exit 1
+			failure "Failed to create fs ${fs_type} on device ${device}"
 		fi
 	fi
 
-	debug "sh -c 'mkdir -p $MOUNT_DIR'"
-	mkdir -p "$MOUNT_DIR" &>/dev/null
+	debug "mkdir -p ${mount_dir}"
+	mkdir -p "${mount_dir}" &>/dev/null
 
-	debug "sh -c 'cat {...} > $MOUNT_DIR-json'"
-	echo "$JSON_OPTIONS" > "$MOUNT_DIR"-json
+	debug "echo {...} > ${mount_dir}-json"
+	echo "${json_options}" > "${mount_dir}-json"
 
-	debug "sh -c 'mount /dev/$DEVICE $MOUNT_DIR'"
-	mount /dev/"$DEVICE" "$MOUNT_DIR" >> $LOG_FILE 2>&1
+	debug "mount /dev/${device} ${mount_dir}"
+	mount "/dev/${device}" "${mount_dir}" >> ${LOG_FILE} 2>&1
 	if [ $? -ne 0 ]; then
-		debug "error during mount"
-		err "{\"status\": \"Failure\", \"message\": \"Could not mount $DEVICE at $MOUNT_DIR\"}"
-		exit 1
+		failure "Could not mount ${device} at ${mount_dir}"
 	fi
 
-	debug "success mount"
-	log "{\"status\": \"Success\"}"
-	exit 0
+	success
 }
 
 dounmount() {
-	MOUNT_DIR="$1"
-	debug "MOUNT_DIR=$MOUNT_DIR"
+	mount_dir="$1"
+	debug "mount_dir=${mount_dir}"
 
-	JSON_OPTIONS=$(cat "$MOUNT_DIR"-json)
+	json_options=$(cat "${mount_dir}-json")
 
-	XENSERVER_PASSWORD=$(echo $JSON_OPTIONS | $JQ -r '.["spangenberg.io/xenserver/password"]')
-	XENSERVER_USERNAME=$(echo $JSON_OPTIONS | $JQ -r '.["spangenberg.io/xenserver/username"]')
-	XENSERVER_HOST=$(echo $JSON_OPTIONS | $JQ -r '.["spangenberg.io/xenserver/host"]')
+	xenserver_password=$(echo "${json_options}" | ${JQ} -r '.["spangenberg.io/xenserver/password"]')
+	xenserver_username=$(echo "${json_options}" | ${JQ} -r '.["spangenberg.io/xenserver/username"]')
+	xenserver_host=$(echo "${json_options}" | ${JQ} -r '.["spangenberg.io/xenserver/host"]')
 
-	MAC=$(cat /sys/class/net/eth0/address)
+	mac=$(cat /sys/class/net/eth0/address)
 	if [ $? -ne 0 ]; then
-		err "{\"status\": \"Failure\", \"message\": \"Could not get mac address\"}"
-		exit 1
+		failure "Could not get mac address"
 	fi
 
-	VM_ID=$(xapi "$XENSERVER_HOST" "$XENSERVER_USERNAME" "$XENSERVER_PASSWORD" vif-list currently-attached="true" params="vm-uuid" MAC="$MAC" --minimal)
+	vm_uuid=$(xapi "${xenserver_host}" "${xenserver_username}" "${xenserver_password}" vif-list currently-attached=true params=vm-uuid MAC=${mac} --minimal)
 	if [ $? -ne 0 ]; then
-		err "{\"status\": \"Failure\", \"message\": \"Could not list vif\"}"
-		exit 1
+		failure	"Could not list vif"
 	fi
-	if [[ -z "$VM_ID" ]]; then
-		err "{\"status\": \"Success\", \"message\": \"Could not find vm\"}"
-		exit 1
+	if [[ -z "${vm_uuid}" ]]; then
+		failure "Could not find VM with MAC ${mac}"
 	fi
 
-	DEVICE=$(findmnt -n -o SOURCE --target "$MOUNT_DIR" 2>>$LOG_FILE | cut -d/ -f3)
+	debug "findmnt -n -o SOURCE --target ${mount_dir} | cut -d/ -f3"
+	device=$(findmnt -n -o SOURCE --target "${mount_dir}" 2>>${LOG_FILE} | cut -d/ -f3)
 	if [ $? -ne 0 ]; then
-		err "{\"status\": \"Failure\", \"message\": \"Could not find mount of $MOUNT_DIR\"}"
-		exit 1
+		failure "Could not find mount of ${mount_dir}"
 	fi
 
-	VBD_ID=$(xapi "$XENSERVER_HOST" "$XENSERVER_USERNAME" "$XENSERVER_PASSWORD" vbd-list currently-attached="true" device="$DEVICE" vm-uuid="$VM_ID" --minimal)
-	if [ $? -ne 0 ]; then
-		err "{\"status\": \"Failure\", \"message\": \"Could not list vbd\"}"
-		exit 1
-	fi
-	if [[ -z "$VBD_ID" ]]; then
-		err "{\"status\": \"Failure\", \"message\": \"Could not find vbd\"}"
-		exit 1
-	fi
+	if [ "${device}" != "mapper" ]; then
+		vbd_uuid=$(xapi "${xenserver_host}" "${xenserver_username}" "${xenserver_password}" vbd-list currently-attached=true device=${device} vm-uuid=${vm_uuid} --minimal)
+		if [ $? -ne 0 ]; then
+			failure "Could not list vbd"
+		fi
+		if [[ -z "${vbd_uuid}" ]]; then
+			failure "Could not find vbd"
+		fi
 
-	umount "$MOUNT_DIR" >> $LOG_FILE 2>&1
-	if [ $? -ne 0 ]; then
-		debug "error during umount"
-		err "{\"status\": \"Failure\", \"message\": \"Could not mount $DEVICE at $MOUNT_DIR\"}"
-		exit 1
-	fi
+		debug "umount ${mount_dir}"
+		umount "${mount_dir}" >> ${LOG_FILE} 2>&1
+		if [ $? -ne 0 ]; then
+			failure "Could not unmount ${device} at ${mount_dir}"
+		fi
 
-	xapi "$XENSERVER_HOST" "$XENSERVER_USERNAME" "$XENSERVER_PASSWORD" vbd-unplug uuid="$VBD_ID"
-	if [ $? -ne 0 ]; then
-		err "{\"status\": \"Failure\", \"message\": \"Could not unplug vbd\"}"
-		exit 1
-	fi
+		xapi "${xenserver_host}" "${xenserver_username}" "${xenserver_password}" vbd-unplug uuid=${vbd_uuid}
+		if [ $? -ne 0 ]; then
+			failure "Could not unplug vbd"
+		fi
 
-	xapi "$XENSERVER_HOST" "$XENSERVER_USERNAME" "$XENSERVER_PASSWORD" vbd-destroy uuid="$VBD_ID"
-	if [ $? -ne 0 ]; then
-		err "{\"status\": \"Failure\", \"message\": \"Could not destroy vbd\"}"
-		exit 1
+		xapi "${xenserver_host}" "${xenserver_username}" "${xenserver_password}" vbd-destroy uuid=${vbd_uuid}
+		if [ $? -ne 0 ]; then
+			failure "Could not destroy vbd"
+		fi
 	fi
 
-	debug "sh -c 'rm -f $MOUNT_DIR-json'"
-	rm -f "$MOUNT_DIR"-json
+	debug "rm -f ${mount_dir}-json"
+	rm -f "${mount_dir}-json"
 
-	debug "unmount success"
-	log "{\"status\": \"Success\"}"
-	exit 0
+	success
 }
 
 xapi() {
-	XENSERVER_HOST="$1"
-	XENSERVER_USERNAME="$2"
-	XENSERVER_PASSWORD="$3"
-	COMMAND="$4"
+	xenserver_host=$1
+	xenserver_username=$2
+	xenserver_password=$3
+	command=$4
 
 	shift 4
 
-	debug "xe $COMMAND $@"
+	debug "xe ${command} $*"
 
-	docker run --rm spangenberg/xapi:latest "$COMMAND" -s "$XENSERVER_HOST" -u "$XENSERVER_USERNAME" -pw "$XENSERVER_PASSWORD" "$@" 2>>$LOG_FILE
+	docker run --rm spangenberg/xapi:latest "${command}" -s "${xenserver_host}" -u "${xenserver_username}" -pw "${xenserver_password}" $* 2>>${LOG_FILE}
 }
 
-debug $*
+debug "$*"
 
 op=$1
 
 shift
 
-case "$op" in
+case ${op} in
 	init)
 		init $*
 		;;
@@ -256,7 +223,7 @@ case "$op" in
 		dounmount $*
 		;;
 	*)
-		err "{\"status\": \"Not supported\"}"
+		err '{"status": "Not supported"}'
+		exit 1
+		;;
 esac
-
-exit 1
